PROCEDURE SORT_YSOKO_BY_UNCHIN (P_KENCD IN NUMBER) IS
  TYPE REC_HINCD IS RECORD (
    HINCD  VARCHAR2(11),
    SUU    NUMBER,
    KOGUTI NUMBER
  );
  TYPE T_SKU_LIST IS TABLE OF REC_HINCD INDEX BY PLS_INTEGER;
  TYPE REC_SIZE_PENDING IS RECORD (
    KONKB    NUMBER,
    HAISOBKB NUMBER,
    KPSIZE   NUMBER,
    SKU_LIST T_SKU_LIST
  );
  TYPE T_SIZE_PENDING IS TABLE OF REC_SIZE_PENDING INDEX BY PLS_INTEGER;
  TBL_PENDING T_SIZE_PENDING;

  TYPE REC_SIZE_KNOWN IS RECORD (
    HAKOSIZE NUMBER,
    HAISOBKB NUMBER
  );
  TYPE T_SIZE_KNOWN IS TABLE OF REC_SIZE_KNOWN INDEX BY PLS_INTEGER;
  TBL_KNOWN T_SIZE_KNOWN;

  TYPE REC_UNCHIN IS RECORD (
    SOKOCD NUMBER,
    RANK   NUMBER,
    AMOUNT NUMBER
  );
  TYPE T_UNCHIN IS TABLE OF REC_UNCHIN INDEX BY PLS_INTEGER;
  TBL_UNCHIN T_UNCHIN;

  v_idx          PLS_INTEGER;
  v_size         NUMBER;
  v_koguti_total NUMBER;
  v_hakokey      VARCHAR2(4000);
  v_hakosize     NUMBER;
  v_unchin_tmp   REC_UNCHIN;

  V_REC_SKUMS     SKUMS%ROWTYPE;
  ERROR_NOT_FOUND EXCEPTION;

  PROCEDURE ADD_TBL_PENDING (P_SKU_REC IN SKUMS%ROWTYPE, P_SUU IN NUMBER) IS
    v_sku_idx PLS_INTEGER;
    v_found   BOOLEAN;
  BEGIN
    -- 個口が１の場合
    IF P_SKU_REC.SKUMS_KOGUTI = 1 THEN
      v_idx := TBL_PENDING.COUNT + 1;
      TBL_PENDING(v_idx).HAISOBKB := P_SKU_REC.SKUMS_HAISOBKB;
    ELSE
      v_found := FALSE;
      FOR j IN 1..TBL_PENDING.COUNT LOOP
        IF TBL_PENDING(j).KONKB    = P_SKU_REC.SKUMS_KONKB AND
           TBL_PENDING(j).HAISOBKB = P_SKU_REC.SKUMS_HAISOBKB AND
          (TBL_PENDING(j).KONKB <> 3 OR TBL_PENDING(j).KPSIZE = P_SKU_REC.SKUMS_KPSIZE) THEN
          v_idx   := j;
          v_found := TRUE;
          EXIT; -- 該当グループが見つかったら抜け出す
        END IF;
      END LOOP;

      -- 該当グループが存在しない場合は新しく要素を追加
      IF NOT v_found THEN
        v_idx := TBL_PENDING.COUNT + 1;
        TBL_PENDING(v_idx).KONKB    := P_SKU_REC.SKUMS_KONKB;
        TBL_PENDING(v_idx).HAISOBKB := P_SKU_REC.SKUMS_HAISOBKB;
        TBL_PENDING(v_idx).KPSIZE   := P_SKU_REC.SKUMS_KPSIZE;
      END IF;
    END IF;

    v_sku_idx := TBL_PENDING(v_idx).SKU_LIST.COUNT + 1;
    TBL_PENDING(v_idx).SKU_LIST(v_sku_idx).HINCD  := P_SKU_REC.SKUMS_SKUCD||P_SKU_REC.SKUMS_COLOR||P_SKU_REC.SKUMS_SIZE; -- 商品コード
    TBL_PENDING(v_idx).SKU_LIST(v_sku_idx).SUU    := P_SUU; -- 数量
    TBL_PENDING(v_idx).SKU_LIST(v_sku_idx).KOGUTI := P_SKU_REC.SKUMS_KOGUTI; -- 個口
  END ADD_TBL_PENDING;

  FUNCTION BUILD_HAKOKEY (P_SKU_LIST IN T_SKU_LIST) RETURN VARCHAR2 IS
    v_sku_list T_SKU_LIST  := P_SKU_LIST;
    v_cnt      PLS_INTEGER := P_SKU_LIST.COUNT;
    v_tmp      REC_HINCD;
    v_key      VARCHAR2(4000) := NULL;
  BEGIN
    -- 商品コード昇順に並べ替え
    FOR a IN 1..v_cnt-1 LOOP
      FOR b IN a+1..v_cnt LOOP
        IF v_sku_list(b).HINCD < v_sku_list(a).HINCD THEN
          v_tmp         := v_sku_list(a);
          v_sku_list(a) := v_sku_list(b);
          v_sku_list(b) := v_tmp;
        END IF;
      END LOOP;
    END LOOP;

    FOR a IN 1..v_cnt LOOP
      v_key := v_key || v_sku_list(a).HINCD || v_sku_list(a).SUU;
    END LOOP;

    RETURN v_key;
  END BUILD_HAKOKEY;

  PROCEDURE CAL_UNCHIN_PRICE (P_HAISOBKB IN NUMBER, P_HAKOKEY IN VARCHAR2) IS
    v_loop_cnt NUMBER := 0;
  BEGIN
    FOR r IN (
      WITH HAKOSMS_CTE AS (
        SELECT SOKOCD, HAKOCD FROM (
          SELECT SOKOCD, HAKOCD, ROW_NUMBER() OVER(PARTITION BY SOKOCD ORDER BY HAKOCD) AS RN FROM HAKOSMS
          WHERE HAKOKEY = P_HAKOKEY
            AND (
              ( P_HAISOBKB NOT IN (1, 2) AND SOKOCD IN (11, 16, 41, 44) ) OR
              ( P_HAISOBKB     IN (1, 2) AND SOKOCD IN (75, 159, 184) )
            )
        ) WHERE RN = 1
      ), HAKO_CTE AS (
        SELECT SOKOCD, HAKOSIZE FROM (
          SELECT S.SOKOCD, (HAKOSIZEH + HAKOSIZET + HAKOSIZEY) / 10 AS HAKOSIZE
          , ROW_NUMBER() OVER(PARTITION BY S.SOKOCD ORDER BY S.HAKOCD) AS RN
          FROM HAKOSMS_CTE S
          INNER JOIN HAKOMS M ON M.SOKOCD = S.SOKOCD AND M.HAKOCD = S.HAKOCD AND M.DELFLG = 0
        ) WHERE RN = 1
      ), T AS (
        SELECT SOKOCD, CDMEI_CDN2 FROM (
          SELECT SOKOCD, CDMEI_CDN2, ROW_NUMBER() OVER(PARTITION BY SOKOCD ORDER BY CDMEI_CDN3 ASC) AS RN
          FROM HAKO_CTE
          INNER JOIN CDMEI 
          ON CDMEI_CDKB = 1039 AND CDMEI_CDA1 = 2 AND CDMEI_DELFLG = 0
          AND (CDMEI_CDN3 >= HAKOSIZE OR CDMEI_CDN3 = 999)
        ) WHERE RN = 1
      ), UNCHIN_CTE AS (
        SELECT * FROM (
          SELECT U.*, ROW_NUMBER() OVER(PARTITION BY UNCMS_SOKOCD ORDER BY UNCMS_KAISIBI DESC, UNCMS_KOSINBI DESC) AS RN
          FROM UNCMS U
          WHERE UNCMS_HAICD = 2
            AND (
              ( P_HAISOBKB NOT IN (1, 2) AND UNCMS_SOKOCD IN (11, 16, 41, 44) ) OR
              ( P_HAISOBKB     IN (1, 2) AND UNCMS_SOKOCD IN (75, 159, 184) )
            )
            AND UNCMS_HAISOBKB = P_HAISOBKB
            AND UNCMS_DELFLG = 0
            AND UNCMS_KAISIBI <= TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD'))
        ) WHERE RN = 1
      )
      SELECT UNCMS_SOKOCD, CASE CDMEI_CDN2 
        WHEN 1  THEN UNCMS_UNCHIN1  WHEN 2  THEN UNCMS_UNCHIN2
        WHEN 3  THEN UNCMS_UNCHIN3  WHEN 4  THEN UNCMS_UNCHIN4
        WHEN 5  THEN UNCMS_UNCHIN5  WHEN 6  THEN UNCMS_UNCHIN6
        WHEN 7  THEN UNCMS_UNCHIN7  WHEN 8  THEN UNCMS_UNCHIN8
        WHEN 9  THEN UNCMS_UNCHIN9  WHEN 10 THEN UNCMS_UNCHIN10
        WHEN 11 THEN UNCMS_UNCHIN11 WHEN 12 THEN UNCMS_UNCHIN12
        WHEN 13 THEN UNCMS_UNCHIN13 WHEN 14 THEN UNCMS_UNCHIN14
        WHEN 15 THEN UNCMS_UNCHIN15 WHEN 16 THEN UNCMS_UNCHIN16
        WHEN 17 THEN UNCMS_UNCHIN17 WHEN 18 THEN UNCMS_UNCHIN18
        WHEN 19 THEN UNCMS_UNCHIN19 WHEN 20 THEN UNCMS_UNCHIN20
        END AS UNCHIN
      FROM UNCHIN_CTE 
      INNER JOIN T ON UNCMS_SOKOCD = T.SOKOCD
    ) LOOP
      v_loop_cnt := v_loop_cnt + 1;

      FOR i IN 1..TBL_UNCHIN.COUNT LOOP
        IF TBL_UNCHIN(i).SOKOCD = r.UNCMS_SOKOCD THEN
          TBL_UNCHIN(i).AMOUNT := TBL_UNCHIN(i).AMOUNT + NVL(r.UNCHIN, 0);
          EXIT;
        END IF;
      END LOOP;
    END LOOP;

    IF v_loop_cnt = TBL_UNCHIN.COUNT THEN
      RAISE ERROR_NOT_FOUND;
    END IF;
  END CAL_UNCHIN_PRICE;

  PROCEDURE CAL_UNCHIN_PRICE_2 (P_HAISOBKB IN NUMBER, P_HAKOSIZE IN NUMBER) IS
    v_loop_cnt NUMBER := 0;
  BEGIN
    FOR r IN (
      WITH T AS (
        SELECT CDMEI_CDN2 FROM (
          SELECT CDMEI_CDN2 FROM CDMEI 
          WHERE CDMEI_CDKB = 1039 AND CDMEI_CDA1 = 2 AND CDMEI_DELFLG = 0
          AND (CDMEI_CDN3 >= P_HAKOSIZE OR CDMEI_CDN3 = 999)
          ORDER BY CDMEI_CDN3 ASC
        ) WHERE ROWNUM = 1
      ), UNCHIN_CTE AS (
        SELECT * FROM (
          SELECT U.*, ROW_NUMBER() OVER(PARTITION BY UNCMS_SOKOCD ORDER BY UNCMS_KAISIBI DESC, UNCMS_KOSINBI DESC) AS RN
          FROM UNCMS U
          WHERE UNCMS_HAICD = 2
            AND (
              ( P_HAISOBKB NOT IN (1, 2) AND UNCMS_SOKOCD IN (11, 16, 41, 44) ) OR
              ( P_HAISOBKB     IN (1, 2) AND UNCMS_SOKOCD IN (75, 159, 184) )
            )
            AND UNCMS_HAISOBKB = P_HAISOBKB
            AND UNCMS_DELFLG = 0
            AND UNCMS_KAISIBI <= TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD'))
        ) WHERE RN = 1
      )
      SELECT UNCMS_SOKOCD, CASE CDMEI_CDN2 
        WHEN 1  THEN UNCMS_UNCHIN1  WHEN 2  THEN UNCMS_UNCHIN2
        WHEN 3  THEN UNCMS_UNCHIN3  WHEN 4  THEN UNCMS_UNCHIN4
        WHEN 5  THEN UNCMS_UNCHIN5  WHEN 6  THEN UNCMS_UNCHIN6
        WHEN 7  THEN UNCMS_UNCHIN7  WHEN 8  THEN UNCMS_UNCHIN8
        WHEN 9  THEN UNCMS_UNCHIN9  WHEN 10 THEN UNCMS_UNCHIN10
        WHEN 11 THEN UNCMS_UNCHIN11 WHEN 12 THEN UNCMS_UNCHIN12
        WHEN 13 THEN UNCMS_UNCHIN13 WHEN 14 THEN UNCMS_UNCHIN14
        WHEN 15 THEN UNCMS_UNCHIN15 WHEN 16 THEN UNCMS_UNCHIN16
        WHEN 17 THEN UNCMS_UNCHIN17 WHEN 18 THEN UNCMS_UNCHIN18
        WHEN 19 THEN UNCMS_UNCHIN19 WHEN 20 THEN UNCMS_UNCHIN20
        END AS UNCHIN
      FROM UNCHIN_CTE CROSS JOIN T
    ) LOOP
      v_loop_cnt := v_loop_cnt + 1;

      FOR i IN 1..TBL_UNCHIN.COUNT LOOP
        IF TBL_UNCHIN(i).SOKOCD = r.UNCMS_SOKOCD THEN
          TBL_UNCHIN(i).AMOUNT := TBL_UNCHIN(i).AMOUNT + NVL(r.UNCHIN, 0);
          EXIT;
        END IF;
      END LOOP;
    END LOOP;

    IF v_loop_cnt = TBL_UNCHIN.COUNT THEN
      RAISE ERROR_NOT_FOUND;
    END IF;
  END CAL_UNCHIN_PRICE_2;

--ここから⭐️
BEGIN
  -- 箱サイズがわかる商品とわからない商品で分類する。
  FOR i IN 1..TBL_SKUMS.COUNT LOOP
    SKUMS_FIND_SECT3(TBL_SKUMS(i).REC_SKUCD, TBL_SKUMS(i).REC_COLOR, TBL_SKUMS(i).REC_SIZE, V_REC_SKUMS);

    IF V_REC_SKUMS.SKUMS_KOGUTI < 1 THEN
      ADD_TBL_PENDING( V_REC_SKUMS, TBL_SKUMS(i).REC_SUU );
    ELSIF V_REC_SKUMS.SKUMS_KOGUTI = 1 THEN
      IF V_REC_SKUMS.SKUMS_JIKAFLG = 1 THEN
        v_idx  := TBL_KNOWN.COUNT + 1;
        v_size := (V_REC_SKUMS.SKUMS_KPSIZEH + V_REC_SKUMS.SKUMS_KPSIZET + V_REC_SKUMS.SKUMS_KPSIZEY) / 10;
        TBL_KNOWN(v_idx).HAKOSIZE  := v_size;
        TBL_KNOWN(v_idx).HAISOBKB  := V_REC_SKUMS.SKUMS_HAISOBKB;
      ELSE
        ADD_TBL_PENDING( V_REC_SKUMS, TBL_SKUMS(i).REC_SUU );
      END IF;
    ELSE
      RETURN;
    END IF;
  END LOOP;

  -- 箱未確定の中から個口合計が1を超えるかチェック
  FOR g IN 1..TBL_PENDING.COUNT LOOP
    v_koguti_total := 0;
    FOR s IN 1..TBL_PENDING(g).SKU_LIST.COUNT LOOP
      v_koguti_total := v_koguti_total
        + TBL_PENDING(g).SKU_LIST(s).KOGUTI * TBL_PENDING(g).SKU_LIST(s).SUU;
    END LOOP;

    IF v_koguti_total > 1 THEN
      RETURN;
    END IF;
  END LOOP;

  -- TBL_UNCHINの初期化
  FOR i IN 1..WK_YSOKO.COUNT LOOP
    TBL_UNCHIN(i).SOKOCD := WK_YSOKO(i-1).SOKOCD;
    TBL_UNCHIN(i).RANK   := i;
    TBL_UNCHIN(i).AMOUNT := 0;
  END LOOP;

  -- 箱未確定の運賃を計算する
  FOR g IN 1..TBL_PENDING.COUNT LOOP
    v_hakokey := BUILD_HAKOKEY(TBL_PENDING(g).SKU_LIST);
    CAL_UNCHIN_PRICE( TBL_PENDING(g).HAISOBKB, v_hakokey );
  END LOOP;

  -- 箱既知の運賃を計算する
  FOR g IN 1..TBL_KNOWN.COUNT LOOP
    CAL_UNCHIN_PRICE_2( TBL_KNOWN(g).HAISOBKB, TBL_KNOWN(g).HAKOSIZE );
  END LOOP;

  -- 合計運賃が安い順にTBL_UNCHINを並べ替える。
  FOR a IN 1..TBL_UNCHIN.COUNT - 1 LOOP
    FOR b IN a+1..TBL_UNCHIN.COUNT LOOP
      IF TBL_UNCHIN(b).AMOUNT < TBL_UNCHIN(a).AMOUNT
         OR (TBL_UNCHIN(b).AMOUNT = TBL_UNCHIN(a).AMOUNT AND TBL_UNCHIN(b).RANK < TBL_UNCHIN(a).RANK) THEN
        v_unchin_tmp  := TBL_UNCHIN(a);
        TBL_UNCHIN(a) := TBL_UNCHIN(b);
        TBL_UNCHIN(b) := v_unchin_tmp;
      END IF;
    END LOOP;
  END LOOP;

  -- 並べ替え結果をWK_YSOKOへ反映する
  FOR i IN 1..TBL_UNCHIN.COUNT LOOP
    WK_YSOKO(i-1).SOKOCD := TBL_UNCHIN(i).SOKOCD;
  END LOOP;

EXCEPTION
  WHEN ERROR_NOT_FOUND THEN
    RETURN;
END SORT_YSOKO_BY_UNCHIN;
